# Generated by Django 3.0.8 on 2020-08-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_add',
            new_name='updated_at',
        ),
    ]
